# Generated by Django 4.1.7 on 2023-08-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionnaire",
            name="apport",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="actionnaire",
            name="pourcentage",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
