# Generated by Django 4.1.7 on 2023-08-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0004_alter_transactionpret_agent"),
    ]

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=100)),
                ("license_key", models.CharField(max_length=50, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
